#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor eDP -d 1 2 3 4 5
# bspc monitor HDMI-A-0 -d 6 7 8 9 10

INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

monitor_add() {
  bspc desktop Desktop --remove
  bspc desktop 6 --to-monitor "$EXTERNAL_MONITOR"
  bspc desktop 7 --to-monitor "$EXTERNAL_MONITOR"
  bspc desktop 8 --to-monitor "$EXTERNAL_MONITOR"
  bspc desktop 9 --to-monitor "$EXTERNAL_MONITOR"
  bspc desktop 10 --to-monitor "$EXTERNAL_MONITOR"
  bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
  bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
}

monitor_remove() {
  bspc desktop 6 --to-monitor "$INTERNAL_MONITOR"
  bspc desktop 7 --to-monitor "$INTERNAL_MONITOR"
  bspc desktop 8 --to-monitor "$INTERNAL_MONITOR"
  bspc desktop 9 --to-monitor "$INTERNAL_MONITOR"
  bspc desktop 10 --to-monitor "$INTERNAL_MONITOR"
  bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --primary --rotate normal --output "$EXTERNAL_MONITOR" --mode 1920x1080 --right-of "$INTERNAL_MONITOR" --rotate normal
    if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
        monitor_add
    fi
else
    xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --rotate normal --output "$EXTERNAL_MONITOR" --off
    if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
        monitor_remove
    fi
fi


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
picom -b

bg_image=~/.wallpaper/wall2.png

nitrogen --set-auto $bg_image &
wal -i $bg_image
. "$HOME/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

xinput set-prop 12 296 1

polybar-msg cmd quit &
polybar &
